### ISSUE TITLE
401 error while calling API

### ISSUE THREAD

**Issue by dicksonarul** [flowable/flowable-engine#1171]
Hi,

i am calling flowable-modeler api by using angular 2 code. Below is the code of angular 2

    createAuthorizationHeader(headers: Headers) {
        headers.append('Authorization', 'Basic ' +
          btoa('admin:test')); 
          headers.append('Content-Type', 'application/json;charset=UTF-8');
      }
    getModel(): Observable<any> {
        var apiUrl = 'http://localhost:8080/flowable-modeler/api/editor/models/';
        let headers = new Headers();
        this.createAuthorizationHeader(headers);
        let OPTIONS = new RequestOptions({ headers: headers });
        return this.http.get(apiUrl, OPTIONS).map(response => response.json());
    }

i am calling this api to get all models in flowable.

i am getting return data i.e list of model from above url in postman or directly in browser

But i am getting below error while calling it from angular 2

"Failed to load http://localhost:8080/flowable-modeler/api/editor/models/: Response for preflight has invalid HTTP status code 401."

Kindly advice what can be done to fix the issue

**Comment by tijsrademakers** [comment]
Hi,

If the rest call works from Postman and the browser, then the problem is in the Angular 2 code. Maybe best to ask this question on an Angular forum, because the Flowable Model REST API just uses standard basic auth authentication and that should work fine like you experienced from Postman and the browser.
