### ISSUE TITLE
About cancelActivityId

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#1172]
Hi:
      Flowable6.2 + provides the ability to unactivate the active node, open the active node, and change the state，I think this is a violation of the BPMN specification.
     This method is for CMMN?Should I use this method in BPMN,Or where any node jump should be applied.

Thank you for helping me out.:)

**Comment by tijsrademakers** [comment]
Hi,

These kind of questions are best asked on the Flowable forum.
Can you create a post on the forum, and explain which API calls you are talking about exactly? Is it the change state functionality that was added in 6.2? If so, then no this is not a "violation" of the spec, it's a Flowable specific addon to bpmn, to make it more flexible when that's needed. 
So no, this is not meant for CMMN (although we might add the same functionality there as well). It's perfectly fine to use the change state functionality if needed, that's why we added it to the BPMN engine API :-)
