### ISSUE TITLE
Help with spring beans

### ISSUE THREAD

**Issue by johnflavin** [flowable/flowable-engine#1178]
Hi. I'm just getting started with Flowable. I hope this question is easy to answer and I'm missing something obvious.

I'm using flowable with spring, but I'm not using the spring XML configuration, I'm configuring all my spring beans and such in code. (I'm also not using spring boot, because I eventually want to integrate flowable into an existing spring application.)

My problem is this. I can wire up everything such that I can deploy process definitions and run process instances. :+1: But when I run a process instance from a process definition that references a bean, it fails. Can't find the bean.

I can verify that spring has an instance of the bean. I haven't explicitly given my process engine any beans, which according to the flowable docs means it should have all the beans. But when I try to get the beans from the process engine, it has nothing. Example:
```java
final Map<Object, Object> beans = ((SpringProcessEngineConfiguration)processEngine.getProcessEngineConfiguration()).getBeans();
assertThat(beans, hasKey("the name of the bean I want"));
```
This assertion fails. The map of beans is empty.

Is there something else I need to do here, or something I have done incorrectly?

I have set up a simple test project so you can replicate/examine this: https://github.com/johnflavin/flowable-spring-test. I do the configuration in [FlowableHelloWorldTestConfig](https://github.com/johnflavin/flowable-spring-test/blob/master/src/test/java/org/flavin/config/FlowableHelloWorldTestConfig.java) and run the test in [FlowableHelloWorldTest](https://github.com/johnflavin/flowable-spring-test/blob/master/src/test/java/org/flavin/helloWorld/FlowableHelloWorldTest.java).

**Comment by DennisFederico** [comment]
Hello John,

I'm not sure if getBeans() should do what you expect. But your problem is not running a process that references a bean.

The bean is accessible, as expected in the Spring context, your code `peconfig.getApplicationContext().getBean("printer")` retrieves it fine

You still need to "pass" it as variable to the execution for the expression to be properly evaluated ... e.g. `runtimeService.startProcessInstanceById(processId, Collections.singletonMap("printer", springPrinterBean))` 

Printer should be Serializable

Also, serviceTask gets executed almost immediately when you start the process and then the process will end, you wont be able to manually complete the task in your code.

I hope this helps you.

Regards

**Comment by tijsrademakers** [comment]
Hi John and Dennis,

Using the Spring bean in an expression like you did should be ok. It’s not necessary at all to pass it as a variable. I’ll give your example project a try and see what can be the issue. 

Best regards

**Comment by DennisFederico** [comment]
Hi John,

Have you tried fetching the ProcessEngine via ProcessEngineFactoryBean instead of 
[https://www.flowable.org/docs/userguide/index.html#springintegration](url)

Something similar to this crude code snippet works...
`SpringProcessEngineConfiguration processEngineConfiguration = new SpringProcessEngineConfiguration();
        processEngineConfiguration.setTransactionManager(transactionManager);
        processEngineConfiguration.setDataSource(dataSource);
        processEngineConfiguration.setDatabaseSchemaUpdate("true");
        processEngineConfiguration.setApplicationContext(ctx);

        ProcessEngineFactoryBean processEngineFactoryBean = new ProcessEngineFactoryBean();
        processEngineFactoryBean.setProcessEngineConfiguration(processEngineConfiguration);
        processEngineFactoryBean.setApplicationContext(ctx);
        
        ProcessEngine processEngine = processEngineFactoryBean.getObject();`

**Comment by tijsrademakers** [comment]
Exactly the ProcessEngineFactoryBean is the missing piece here. You can use this configuration as an example of how to use it as well:

https://github.com/flowable/flowable-engine/blob/1dfc2ff502d2b462c47d0844e0ce4a2ca79a1e36/modules/flowable-rest/src/test/java/org/flowable/rest/conf/engine/EngineConfiguration.java

Without the ProcessEngineFactoryBean the SpringExpressionManager is not used and the Flowable engine is not ApplicationContextAware. You will see that when you use the ProcessEngineFactoryBean in your config it will work like expected.

**Comment by johnflavin** [comment]
Thanks! I'll give it a try.
