### ISSUE TITLE
ACT_DE_MODEL Missing unique index

### ISSUE THREAD

**Issue by jianlinz** [flowable/flowable-engine#1186]
Hi!
in flowable 6.2.1
ModelsResource.java have a function checkForDuplicateKey i think key is a unique index in ACT_DE_MODEL.
if missing it when i import a bpmn.xml with same key the ACT_DE_MODEL will have same key.
i think is a question. 

Honored to You can see the issue

**Comment by tijsrademakers** [comment]
Hi,

Thanks for raising the issue. A key only has to be unique for the specific model type and for the tenant id. It's pretty much an extra insurance that you don't deploy different models with the same key to the Flowable Engine, because they would be versioned as the same model there. 

Best regards
