### ISSUE TITLE
Increase Galera database compatibility

### ISSUE THREAD

**Issue by smeeus** [flowable/flowable-engine#1244]
For a project I'm currently working on, I got the remark from MariaDB support that each and every table on a Galera cluster needs a primary key (or unique index)

Ref: https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/

> All tables should have a primary key (multi-column primary keys are supported). DELETE operations are unsupported on tables without a primary key. Also, rows in tables without a primary key may appear in a different order on different nodes.

Checking a simple Flowable installation (checked on 6.2.0, 6.3.0 and 6.3.1), there are no primary keys defined for the tables:

* ACT_ADM_DATABASECHANGELOG
* ACT_CMMN_DATABASECHANGELOG
* ACT_CO_DATABASECHANGELOG
* ACT_DE_DATABASECHANGELOG
* ACT_DMN_DATABASECHANGELOG
* ACT_FO_DATABASECHANGELOG

Looking at the tables, I cannot see a single column that would be fit as primary key. MariaDB support also informed me that multiple column primary keys are supported.

What column(s) could/should be used to create a primary key from?
Can a new column for primary key use (with autoincrement) be added safely to these tables?

**Comment by filiphr** [comment]
@smeeus those tables are created by Liquibase (which is what we use to perform the DB updates). I found [this](http://forum.liquibase.org/topic/why-does-databasechangelog-not-have-a-primary-key) which explains why they don't have a primary key. There is also the  [CORE-1909](https://liquibase.jira.com/browse/CORE-1909) in the Liquibase JIRA, which has been closed with a "By Design" resolution.

Actually there is a comment about Galera in there as well. There is also a mentioned workaround for how one can add a primary key to those tables. 

I am not entirely sure that we need to add those primary keys on the Flowable side. However, you can add one manually to those tables. Apparently `(ID, AUTHOR, FILENAME)` can be a primary key.
