### ISSUE TITLE
Paging does not work when I set includeProcessVariables to true

### ISSUE THREAD

**Issue by mdmatthias** [flowable/flowable-engine#1348]
This still gives correct results:
/flowable-rest/service/history/historic-process-instances?size=200&start=600&excludeSubprocesses=true&includeProcessVariables=true

"total": 5845,
"start": 600,
"sort": "processInstanceId",
"order": "asc",
"size": 200

But when I request the next page there are only 10 results:
/flowable-rest/service/history/historic-process-instances?size=200&start=800&excludeSubprocesses=true&includeProcessVariables=true
"total": 5845,
"start": 800,
"sort": "processInstanceId",
"order": "asc",
"size": 10

Anything higher than 810 gives 0 results. 
/flowable-rest/service/history/historic-process-instances?size=200&start=1300&excludeSubprocesses=true&includeProcessVariables=true
"total": 5845,
"start": 1300,
"sort": "processInstanceId",
"order": "asc",
"size": 0

But when I set includeProcessVariables to false it works correctly
/flowable-rest/service/history/historic-process-instances?size=200&start=1300&excludeSubprocesses=true&includeProcessVariables=false
"total": 5845,
"start": 1300,
"sort": "processInstanceId",
"order": "asc",
"size": 200

**Comment by martin-grofcik** [comment]
The problem with `includeProcessVariables` is that we are joining executions and variables in the querying. That's why pagination does not work in that case.

**Comment by mdmatthias** [comment]
But why does it only break after 800 results? if we request for example results 400-600 it works correctly.

**Comment by thevikramray** [comment]
Same issue with me as I have more than 5000 processes. The reason for this is because for performance reason the limit is set to 20000 variable( https://issues.alfresco.com/jira/browse/ACTIVITI-1065). Each of my processes has more than 500 processVariable and for that reason, I am not able to get paginated data for process no more than 200.

Can anyone help me figuring out how to increase this limit?
or
Can I get paginated response to get 2 or 3 variables(firstName, email) with includeProcessVariable=true?

**Comment by filiphr** [comment]
This has been fixed with our rework of how we do paging in PR #2892.
