### ISSUE TITLE
I used Maven to compile Flowable6.4.1, and it never worked.

### ISSUE THREAD

**Issue by mnhy520** [flowable/flowable-engine#1560]
Execute on the command line of Windows 7
cd D:\mycode\flowable-engine-6.4.1
mvn -Pdistro clean install -DskipTests
![image](https://user-images.githubusercontent.com/1035467/51826886-171b3f80-2323-11e9-97d3-eab5c346f229.png)

I tried it a few times, but it didn't work.

**Comment by dbmalkovsky** [comment]
I have a Windows 7 x64 box.  So I downloaded the source zip from [here](https://github.com/flowable/flowable-engine/releases)  and then unzipped it.  

Next I downloaded the Apache Maven 3.6.0 bin zip from [here](https://maven.apache.org/download.cgi?Preferred=ftp://mirror.reverse.net/pub/apache/) and unzipped that file.

Next I set my `java_home` to a JDK 8 version and then entered as you did `mvn -Pdistro clean install -DskipTests.

On my reasonable configured Win7 machine it took 43 minutes to build.

I suspect but can not see in your screen shot that the fetching of jars timed out.  The flowable-mule target has *lots* of dependencies (around 275 of them).

**Comment by mnhy520** [comment]
> I have a Windows 7 x64 box. So I downloaded the source zip from [here](https://github.com/flowable/flowable-engine/releases) and then unzipped it.
> 
> Next I downloaded the Apache Maven 3.6.0 bin zip from [here](https://maven.apache.org/download.cgi?Preferred=ftp://mirror.reverse.net/pub/apache/) and unzipped that file.
> 
> Next I set my `java_home` to a JDK 8 version and then entered as you did `mvn -Pdistro clean install -DskipTests.
> 
> On my reasonable configured Win7 machine it took 43 minutes to build.
> 
> I suspect but can not see in your screen shot that the fetching of jars timed out. The flowable-mule target has _lots_ of dependencies (around 275 of them).

I'm in the same environment as you, but I still failed.Thank you for your reply.

**Comment by filiphr** [comment]
The missing artifact (`net.java.dev.stax-utils:stax-utils:200807020` which can be found at https://mvnrepository.com/artifact/net.java.dev.stax-utils/stax-utils/20080702) is located in the 
[Mulesoft](http://repository.mulesoft.org/releases/) maven repository repository.

Our `flowable-mule` module already has a pointer to that repository
```
<repositories>
    <repository>
        <id>mulesoft-releases</id>
        <name>MuleSoft Releases Repository</name>
        <url>http://repository.mulesoft.org/releases/</url>
        <layout>default</layout>
    </repository>
</repositories>
```

Looking at your image @mnhy520 I can see that you are using some kind of proxy (`nexus-aliyun` which is located at `http://maven.aliyun.com/nexus/content/groups/public`). You probably need to adapt your `settings.xml` in order to exclude the Mulesoft repo from there or you would need to make sure that the proxy also includes the Mulesoft repo.
