### ISSUE TITLE
createChangeActivityStateBuilder & changeState & multi instance parallel

### ISSUE THREAD

**Issue by strongme** [flowable/flowable-engine#1674]
here is the test code and bpmn file :
https://github.com/strongme/flowable-test/tree/master
just run the FlowableTest which expect to pass the test

**Comment by martin-grofcik** [comment]
Hi strongme.

Thank you for the test. It was much easier to reproduce the issue.

1. in the case on migrating multi instanace tasks use `.moveExecutionToActivityId(taskExecution.getParentId(), "startMeeting")` instead of `.moveExecutionsToSingleActivityId(exIds, "startMeeting")`
````
        List<Task> tasksForSubmitOpinion = taskService.createTaskQuery().processInstanceId(processInstanceId).taskDefinitionKey("submitOpinion").active().list();
        assertThat(tasksForSubmitOpinion.size()).isEqualTo(3);

        Execution taskExecution = runtimeService.createExecutionQuery().executionId(tasksForSubmitOpinion.get(0).getExecutionId()).singleResult();

        runtimeService.createChangeActivityStateBuilder()
                .processInstanceId(processInstanceId)
                .moveExecutionToActivityId(taskExecution.getParentId(), "startMeeting")
                .changeState();

````

for additional examples have a look on [ChangeStateForMultiInstanceTest](https://github.com/flowable/flowable-engine/blob/c2c6fb0989216bc7d70bd7dc775a448b8c4ad923/modules/flowable-engine/src/test/java/org/flowable/engine/test/api/runtime/changestate/ChangeStateForMultiInstanceTest.java#L313)

2. support for multiinstance state changes was added in the pull request https://github.com/flowable/flowable-engine/pull/1343. Use [flowable 6.4.1](https://github.com/flowable/flowable-engine/releases/tag/flowable-6.4.1) instead of 6.3.1 

Martin

**Comment by osbornjonny** [comment]
I have tested as @strongme showed case, edit codes as @martin-grofcik say, all test passed.

**Comment by strongme** [comment]
@martin-grofcik i followed your tip end up no problem. thanks 
but as i change the version to 6.4.1, i still need to do the multiinstance state change as you suggest.
any mistakes i had in my test code?
