### ISSUE TITLE
Global datetime format in my project may causes error when i updating model

### ISSUE THREAD

**Issue by sscfaith** [flowable/flowable-engine#1874]
Hi：
I integrated flowable-ui into my springboot project and I have global datetime format (yyyy-MM-dd HH:mm:ss)，so I lost milliseconds。

When I updating model：
![image](https://user-images.githubusercontent.com/23066241/62259628-94924a80-b441-11e9-81e0-897259228c8f.png)
### So I have an error in org.flowable.ui.modeler.rest.app.ModelResource.java:212
![image](https://user-images.githubusercontent.com/23066241/62259645-9fe57600-b441-11e9-8ba7-2af555f09031.png)

**Comment by tijsrademakers** [comment]
This mean you integrated the Flowable Modeler as well in your spring boot project? I would advise to keep that as a separate app if possible. The update logic needs the time to be milisecond precise to make sure the model didn't change in the meantime. Another possibility would be that a property is added to disable this check so that it will still work for you.
