### ISSUE TITLE
Compensation Boundary Event issue in BPMN XML definition

### ISSUE THREAD

**Issue by Kunxian615** [flowable/flowable-engine#2034]
![image](https://user-images.githubusercontent.com/33412590/69614401-071cdb00-106e-11ea-9b5f-efb65f8e296b.png)

**Comment by Kunxian615** [comment]
version is 6.4.2 
![image](https://user-images.githubusercontent.com/33412590/69614614-56630b80-106e-11ea-9010-6537ec7c5282.png)

**Comment by tijsrademakers** [comment]
Hi,

The problem is that association elements should be at the bottom of the process / sub process definition. So your serviceTask element should be above the association element. You can find some working compensation examples in our unit test resources like:

https://github.com/flowable/flowable-engine/blob/eeebfd23af3571741b60e3f663f17c0ecc50a812/modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.testMultipleCompensationCatchEventsCompensationAttributeMissingFails.bpmn20.xml

**Comment by Kunxian615** [comment]
thank you. It should be noted here that <association&gt; should be placed on the last line of bpmn





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tijs Rademakers"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午5:05
收件人:&nbsp;"flowable/flowable-engine"<flowable-engine@noreply.github.com&gt;;
抄送:&nbsp;"我在这"<670374379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [flowable/flowable-engine] Compensation Boundary Event issue in BPMN XML definition (#2034)



Hi,
 The problem is that association elements should be at the bottom of the process / sub process definition. So your serviceTask element should be above the association element. You can find some working compensation examples in our unit test resources like:
 https://github.com/flowable/flowable-engine/blob/eeebfd23af3571741b60e3f663f17c0ecc50a812/modules/flowable-engine/src/test/resources/org/flowable/engine/test/bpmn/event/compensate/CompensateEventTest.testMultipleCompensationCatchEventsCompensationAttributeMissingFails.bpmn20.xml
