### ISSUE TITLE
Start and End Date of Process Instance

### ISSUE THREAD

**Issue by jisqaqov** [flowable/flowable-engine#230]
Hello Tijs. Could you please, consider, addition of fields "Initiator", "StartDate", "CompletionDate" in process instance.
Initiator -  is a string field and point by whom process instance started. (it is a feature in jbpm).
StartDate - is a DateTime field to point when exactly process instance started. I know that i can obtain information from history. But i think it is a redundant and easier to get info from process instance. (it has in camunda bpm)
CompletionDate - is a DateTime field to point when process instance completed. (it has in camunda bpm)

**Comment by tijsrademakers** [comment]
Ehm, if you look in the ProcessInstance interface you see a startUserId and startTime property which already provide most of what you are looking for. Also HistoricProcessInstance provides both properties as well, but also the end time. The runtime ProcessInstance interface can't have an end time because it's always a running process instance.
