### ISSUE TITLE
cannot see forms in flowable-modeler/#/forms when I use the api of Create a model（POST repository/models）

### ISSUE THREAD

**Issue by colin5nixon** [flowable/flowable-engine#2335]
when I use the api of Create a model（POST repository/models）, ACT_DE_MODEL has no data added and there is no new form in the app(flowable-modeler/#/forms). How to create a form using api that I can see in the app(flowable-modeler/#/forms)?（flowable 6.5.0）

**Comment by vzickner** [comment]
Hi @colin5nixon, I think that question fits better into the [forum](https://forum.flowable.org/).

There is a separate API, database tables etc. for forms. You can find the [forms REST api documentation here](https://flowable.com/open-source/docs/form/ch07-REST/#create-a-new-deployment)

**Comment by tijsrademakers** [comment]
Hi @colin5nixon,
To create a new model for the Flowable Modeler you can use this REST API of the Modeler:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-modeler/flowable-ui-modeler-rest/src/main/java/org/flowable/ui/modeler/rest/api/ApiModelsResource.java

The repository/models API is not used by the Flowable Modeler but by the Engine, so that's why you don't see the model appearing in the Flowable Modeler.

Best regards
