### ISSUE TITLE
Parallel gateway with an exclusive gateway in one of the forks doesn't merge at the end

### ISSUE THREAD

**Issue by verheyenkoen** [flowable/flowable-engine#2383]
**Describe the bug**
I have a workflow with a parallel gateway with two forked executions. In one of these executions I also have an exclusive gateway. In the end all sequenceFlows end in the joining parallel gateway.

When both parallel executions reach the joining point, execution is halted and the flow is stuck. When I query the REST API for executions on that process instance I find 3, 1 parent and 2 children (of that parent). The activiti ID's match with what is in the code.

![image](https://user-images.githubusercontent.com/599538/83904167-adeddc80-a75f-11ea-801f-117a4f9f9fe7.png)

Note that the last blue node is the parallel gateway.

I worked around this by also adding an ending/merging/joining exclusive gateway to join the top fork which should not be necessary as there is only one execution at that point. I also can't find anything in the docs that point out that this would be necessary. To the contrary the docs state:

> Note that a parallel gateway does not need to be 'balanced' (a matching number of incoming/outgoing sequence flow for corresponding parallel gateways).

Also, the docs on exclusive gateways don't mention that an exclusive gateway should be concluded with another exclusive gateway.

![image](https://user-images.githubusercontent.com/599538/83904380-0ae99280-a760-11ea-9963-94453454de38.png)

**Expected behavior**
The flow should proceed when 2 paths join in the end parallel gateway. The merging parallel gateway shouldn't care that there are 3 incoming sequences while there were only 2 at the start, as 2 of those 3 are conditional.

**Code**
N/A

**Additional context**
I tested in both Activiti 5 and Flowable 6. This behaviour occurs in both.

**Comment by tijsrademakers** [comment]
Hi Koen,

The issue is not that an exclusive gateway needs to be balanced. The problem is that in the first BPMN model you have 3 incoming sequence flows into the join parallel gateway. Each of the incoming sequence flows of a parallel gateway need to be taken until the parallel gateway will complete and move on to the next element in the model. Therefore it works fine with the balanced exclusive gateway because then, correctly, it only has 2 incoming sequence flows into the join parallel gateway.

Best regards
