### ISSUE TITLE
DefaultHistoryManager.recordIdentityLinkDeleted always fails because of wrong id

### ISSUE THREAD

**Issue by billerby** [flowable/flowable-engine#2664]
**Describe the bug**
Faulty records in the act_hi_identitylink table which causes unexpected behaviour for us when later on querying for historical tasks and processes

The call to deleteHistoricIdentityLink is not fed with the id from the HistoricalIdentityLink counterpart but from the "active one".

**Expected behavior**
I would have expected a row to be deleted from the act_hi_identitylink table

**Code**
```
    @Override
        public void recordIdentityLinkDeleted(IdentityLinkEntity identityLink) {
            String processDefinitionId = getProcessDefinitionId(identityLink);

            if (isHistoryLevelAtLeast(HistoryLevel.AUDIT, processDefinitionId)) {
        processEngineConfiguration.getIdentityLinkServiceConfiguration().getHistoricIdentityLinkService().deleteHistoricIdentityLink(identityLink.getId());
            }
        }

```

**Additional context**
Flowable version 6.5.0
Postgres
Using spring boot.

**Comment by billerby** [comment]
This bug also exists for delete historical entity links...

```
    @Override
    public void recordEntityLinkDeleted(EntityLinkEntity entityLink) {
        String processDefinitionId = getProcessDefinitionId(entityLink);

        if (isHistoryLevelAtLeast(HistoryLevel.AUDIT, processDefinitionId)) {
            processEngineConfiguration.getEntityLinkServiceConfiguration().getHistoricEntityLinkService().deleteHistoricEntityLink(entityLink.getId());
        }
    }
```

**Comment by filiphr** [comment]
Can you please describe what you mean by faulty records and and how does the delete fail.

Using the id from the runtime identity links and entity links is correct since the historic parts are created with those ids:

## Creating historic identity link
https://github.com/flowable/flowable-engine/blob/e16028d255474db3eee966911cd3af7568ac5507/modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java#L381-L398

## Creating historic identity link
https://github.com/flowable/flowable-engine/blob/e16028d255474db3eee966911cd3af7568ac5507/modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java#L410-L433

**Comment by billerby** [comment]
Filip, a bit embarrasing for me this.. 

The reason for all errors and inconsistency was a FlowableEventListener that was registered both globally and in the process which caused a race condition (the listener are adding and removing IdentityLinks based on variable updates) resulting in a messed up act_hi_identity table. No links removed, only new ones added. I'll close it.
