### ISSUE TITLE
Flowable all in one/ change server port

### ISSUE THREAD

**Issue by hamzapoly** [flowable/flowable-engine#2743]
Hello,

I tried to use flowable services in seperate docker containers but I faced the problem of redirection back after successful authentication in "flowable-idm".
So I'd like to use the "flowable/all-in-one" as redirection works fine .
However I'd like to change the expose port to 80 instead of 8080, I can't see the possible environments in the dockerhub page.
I'm not sure if it's even possible.
SERVER_PORT=80 (did not work)
If also possible to specify the IDM redirect URL thanks to help me with the required environement as :
FLOWABLE_COMMON_APP_IDM-REDIRECT-URL (did not work also)
Thanks in advance,
Hamza

**Comment by yvoswillens** [comment]
Hi,

why don't u use the container port mapping?

f.e. `-p1234:8080`

Yvo

**Comment by hamzapoly** [comment]
In fact I'm using haproxy as a reverse proxy for some CORS headers, and now I added the bind on :8080 (so no problem with 8080)
but the redirection issue is still there as I'm using domain names (traefik) redirections always use localhost:8080/flowable-task
instead of (for example flowable.local/flowable-task)
when I change the url in browser it works though so I just need to specify this url in environment same as in docker seperate images. Possible ?

**Comment by yvoswillens** [comment]
In the latest release there are no separate UI app images anymore.
There is the Flowable UI image (https://hub.docker.com/r/flowable/flowable-ui)
The authentication and cookie handling will probably not be an issue here because of the shared webfoot.

With this release you can provide application properties (Flowable specific and / or Spring properties) as command line arguments. For example.

```
docker run -p8080:8123 flowable/flowable-ui --server.port=8123
```

Could you please try this? If you need help with this or anything related please start a forum topic.
And create GitHub issues when you bump into a reproducible bug.

Yvo
