### ISSUE TITLE
intermediateCatchEvent can't support timeCycle 

### ISSUE THREAD

**Issue by fishdemon** [flowable/flowable-engine#2761]
this is my code

```xml
<intermediateCatchEvent id="sid-d73d5c2a-6a6a-44c7-b805-edfefb829d3e">
        <timerEventDefinition>
            <timeCycle>R2/2021-01-07T17:25:16/PT3S</timeCycle>
        </timerEventDefinition>
</intermediateCatchEvent>
```

but the intermediateCatchEvent only run one time

**Comment by jbarrez** [comment]
What would be the behaviour when using repetition here? The process instance has already moved on when the timer fires.

**Comment by jueying93** [comment]
I tested IntermediateTimerEventRepeatCompatibilityTest.testRepeatWithEnd.bpmn20.xml file  ,when i modified data (<timeCycle>R1/PT1H/${EndDateForCatch1}</timeCycle>  to  <timeCycle>R5/PT1H/${EndDateForCatch1}</timeCycle>),but   timer only runed once.
and  table  ACT_RU_TIMER_JOB field "REPEAT_"  is null.

**Comment by jbarrez** [comment]
Yes, because it' an intermediate catch event. Once the timer fires, the execution continues and leaves the intermediate timer event. 

From the BPMN spec: 
When a token arrives at an Intermediate Event that is placed within the normal flow of a Process, one of two things will happen:
• If the Event is used to “throw” the Event trigger, then trigger of the Event will immediately occur (e.g., the Message will be sent) and the token will move down the outgoing Sequence Flow.
• If the Event is used to “catch” the Event trigger, then the token will remain at the Event until the trigger occurs (e.g., the Message is received). Then the token will move down the outgoing Sequence Flow.

i.e. we're in the second case here: the token has moved down the outgoing sequence flow.

What you're describing is possible in CMMN though with a timer event listener: https://flowable.com/open-source/docs/cmmn/ch06-cmmn/#event-listeners

**Comment by fishdemon** [comment]
ok , thanks .
what can i do to achieve the desire scene（R2/2021-01-07T17:25:16/PT3S）?     
can i implement a new intermediate instead of original?

**Comment by jbarrez** [comment]
What you want is not that easy to do in a BPMN process. The closest you can get is a timer start event + event subprocess.

It is easy in CMMN though.

Let's close this issue (as it's working as intented) and continue the discussion in the forum https://forum.flowable.org/

**Comment by fishdemon** [comment]
ok, thank you!
but i can't open https://forum.flowable.org/ temporarily
