### ISSUE TITLE
Order TimerJobs by DUEDATE_ ASC 

### ISSUE THREAD

**Issue by vorbidan** [flowable/flowable-engine#2765]
**Is your feature request related to a problem? Please describe.**
When AcquireTimerJobsCmd  retrieves a page of TimerJobs to  acquire, it would make sense to order the result set retrieved from the database by the DUEDATE_, as we probably want to prioritize the oldest ones to be executed first.

We usually have quite a few TimerJobs which need to be scheduled quite often. Without ordering the oldest ones to be prioritized we see delays in those being executed.

**Describe the solution you'd like**
Modify `selectTimerJobsToExecute` to include an `ORDER BY` clause:
after line 167 in https://github.com/flowable/flowable-engine/blob/e84c5889e078cb8aef83a9ffc7e545773d87d7b7/modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/mapping/entity/TimerJob.xml#L167
add 
`order by DUEDATE_ ASC`

This would guarantee oldest TimerJobs to be piked up first

**Describe alternatives you've considered**

Increasing `MaxTimerJobsPerAcquisition`, but it does not really solve the issue, and rather exaggerates it with dirty reads and optimistic lock exceptions.

**Comment by tijsrademakers** [comment]
Hi, thanks for the clear issue description. Adding an order by makes sense for use case where a lot of timer jobs are executed, but also makes the query slower because of the sorting. We are working on a change where the max timer jobs per acquisition would be possible to be increased without having more optimistic lock exceptions. So we are looking into this direction first and let's see if you still have issues with the timer jobs after this and then please reopen the issue.
