### ISSUE TITLE
Start Timer Event doesn't start the process

### ISSUE THREAD

**Issue by bob-cy** [flowable/flowable-engine#2866]
**Describe the bug**
I have used the flowable-ui 6.6.0 to define and run some processes with Start Timer Event and HTTP Task. After I deployed them, I found that the deployed processes cannot be started by Start Timer Event, and I can't even start them manually.
The steps to reproduce the bug:
1. start the flowable-ui application
2. Define four similar processes, as follows (see **code**). HTTP Task just visit any normal url.
> Start Timer Event --> Script Task --> HTTP Task --> End Event
3. Add four processes to an app and deploy them
4. After deployment, these four processes were supposed to be automatically started every minute, but they did not actually start. At the same time, these four processes cannot be started manually.

*This issue didn't happen in flowable-ui 6.5.0.*

**Expected behavior**
The four deployed processes should be started once every minute.

**Code**
Time cycle in Start Timer Event : `0 0/1 * * * ?`
Groovy code in Script Task: `System.out.println("test TimerEvnet1");`

**Additional context**
Flowable version: `flowable-ui 6.6.0`
database: `default`

**Comment by tijsrademakers** [comment]
Hi, please attach the app model zip so we can reproduce the issue.

**Comment by bob-cy** [comment]
[testTimerEventApp.zip](https://github.com/flowable/flowable-engine/files/6247226/testTimerEventApp.zip)
@tijsrademakers Thanks for answering my issue, this is the app model zip.

**Comment by bob-cy** [comment]
Modifying the "spring.task.execution.pool.core-size=5" in the configuration file and restarting the service can solve this problem, but adding another process that is the same will still cause this bug.

**Comment by MasterLover** [comment]
you are using cron expression?

**Comment by 4gsim** [comment]
The problem is with the "parallelInSameTransaction" flag in the HTTP task. If you set it to true, it will try to execute the task in the same pool as the one for the processes. But that pool will always be full waiting for at least one process to finish because no process will finish because they are waiting for their HTTP tasks.

**Comment by filiphr** [comment]
Thanks for the explanation @4gsim.

@bob-cy there are different ways that you could go ahead and fix this:

* If you are in the Spring world use the Spring WebClient backed HTTP Task instead of the Apache HTTP Components one. This is done automatically if you don't have the Apache HTTP Client on your classpath, but you do have Spring WebClient. Or you can explicitly set the `FlowableHttpClient` in the `HttpClientConfig` by using `SpringWebClientFlowableHttpClient`.
* Add a custom `AsyncTaskInvoker` in the process engine configuration which would use a different (flowable) `AsyncTaskExecutor` than the one used for the async jobs

**Comment by bob-cy** [comment]
Thanks for the explanation. Since the radio button of the ui interface of `flowable-ui 6.6.0` has bugs(so "parallelInSameTransaction" flag cannot be set to true) and I don’t want to modify the source code, is there a way to solve this problem by only modifying the configuration without modifying the source code?

**Comment by bob-cy** [comment]
Reasonably set the values of the following parameters:
spring.task.execution.pool.core-size=xx
spring.task.execution.pool.queue-capacity=xx
spring.task.execution.pool.max-size=xx
