### ISSUE TITLE
flowable-rest WAR application not working with version 10 of Apache Tomcat

### ISSUE THREAD

**Issue by tboyeux** [flowable/flowable-engine#2939]
**Describe the bug**
Trying to deploy the flowable-rest app using the [documentation](https://flowable.com/open-source/docs/bpmn/ch02-GettingStarted/#getting-started-with-the-flowable-rest-api)  and version 10 of Tomcat does not work.

All API requests end up with 404 errors: 
`The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.`

When launching the Tomcat instance, the flowable-rest app does not seem to be loaded correctly, as the only console output is : 

```
29-May-2021 12:59:15.076 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\flowable-rest.war]
29-May-2021 12:59:18.232 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
29-May-2021 12:59:18.343 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\flowable-rest.war] has finished in [3,267] ms
```
No other console output mentioning Flowable is listed.

When downgrading from Tomcat 10 to Tomcat 9, everything works correctly.

**Expected behavior**
Two options:
- Clearly mention in the documentation that Tomcat 10 is not supported out-of-the-box for the flowable-rest WAR app
- Or make the flowable-rest app work on Tomcat 10 :)

**Additional context**
Flowable version: Flowable 6.6.0, out-of-the-box config with no change 
Tomcat version: Apache Tomcat  10.0.6, out-of-the-box install with no change

**Comment by filiphr** [comment]
The flowable-rest WAR application is based on Spring Boot. The reason why it doesn't work is due to the fact that Tomcat 10 switches from the `javax.*` to `jakarta.*` namespace. From a flowable point of view we can't do much and have to wait for the frameworks we use to do the switch. In this case this would be Spring Framework. You can follow https://github.com/spring-projects/spring-framework/issues/25354 for more information.

Due to this being such a big and breaking change the Tomcat team is maintaining both Tomcat 9.x and 10.x.. 

We will look into adding the information that the flowable-rest WAR application is based on Spring Boot.
