### ISSUE TITLE
Could not create connection...For MySQL

### ISSUE THREAD

**Issue by Gannalyo** [flowable/flowable-engine#3043]
I tried to change datasource from h2 to mysql after installing flowable, the log printed 'could not create connection...' and unsuccessfully to start flowable.

Steps:
1.docker pull flowable/flowable-ui
2.docker run -itd -p 8080:8080 flowable/flowable-ui  (successfully to access http://localhost:8080/flowable-ui)
3.edit flowable-default.properties (refer to the below screenshot)
4.copy 'mysql-connector-java-5.1.47.jar' to 'app/WEB-INF/lib'  (unsuccessfully...)
5.I also tried to use 'flowable/all-in-one' and 'mysql-connector-java-8.0.22.jar'  (did not work..)

flowable's version is the latest.

BTW, my mysql server can be accessed by the Navicat and my other apps normally, I checked configs(driver,url,username,password) again and again.

![image](https://user-images.githubusercontent.com/34175244/132984108-bbbb3631-ac33-4889-9128-1ef71f2edf46.png)

**Comment by dbmalkovsky** [comment]
Filip has previously noted that there are "some issues with versions after 8.0.19"' see https://github.com/flowable/flowable-engine/pull/2988#discussion_r684990974

**Comment by Gannalyo** [comment]
> Filip has previously noted that there are "some issues with versions after 8.0.19"' see [#2988 (comment)](https://github.com/flowable/flowable-engine/pull/2988#discussion_r684990974)

I have read [#2988](https://github.com/flowable/flowable-engine/pull/2988#discussion_r684990974), it seems like an integration between flowable and springboot. However, I installed flowable and change datasource only, [#2988](https://github.com/flowable/flowable-engine/pull/2988#discussion_r684990974) could not resolve my problem。

**Comment by filiphr** [comment]
You'll need to share a bit more information about what isn't working. Can you share the entire stacktrace?

>, the log printed 'could not create connection...'

This usually indicates that there is a problem connecting to the database, so you'll need to see that. Is the username / password correct, is the IP correct, etc.

Closing this for now since we do not believe that this is a problem with Flowable. You can also use the [Flowable Forum](https://forum.flowable.org/) where the community might be able to help out better with similar messages.
