### ISSUE TITLE
The instance ID has been returned, but the database has not been saved successfully, and there is no exception log.

### ISSUE THREAD

**Issue by github24518** [flowable/flowable-engine#3116]
Question:
When the tasklistener executes abnormally, the process instance is not recorded and cannot be queried in the flowale UI instance list, but can be queried when the execution is successful.

Is this a flowable bug and how to deal with it?

**Comment by tijsrademakers** [comment]
@github24518 , when a task listener throws an exception, the current transaction will be rolled back. If you want to keep the process instance then you can make the start event async for example, because then the exception will result in rolling back only until the start event and the process instance will be available in the database because it was created in another transaction.
