### ISSUE TITLE
linux SetProcessInstanceNameCmd.execute error in 6.5.0

### ISSUE THREAD

**Issue by zywhmj** [flowable/flowable-engine#3240]
**Describe the bug**
flowable 6.5.0 version
Linux has an error starting the Flowable process ：
![1647588961(1)](https://user-images.githubusercontent.com/15363766/158957072-0246c06d-186c-408e-ac1e-cefde5e30939.png)

**Expected behavior**

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by tijsrademakers** [comment]
The error message clearly explains that the given id value is not a process instance id but a child execution id. Make sure that you pass a correct process instance id.

**Comment by zywhmj** [comment]
but Mysql has no record of this

**Comment by zywhmj** [comment]
> 但是Mysql没有这方面的记录



> 错误消息清楚地说明给定的 id 值不是流程实例 ID，而是子执行 ID。请确保传递正确的流程实例 ID。

**Comment by zywhmj** [comment]
When does this happen
![1647592204](https://user-images.githubusercontent.com/15363766/158964490-35702544-1860-4fed-84f6-c89ed9db2902.png)

**Comment by tijsrademakers** [comment]
You have done detailed debugging and this exactly tells what I provided as feedback in my previous comment. The id value that you are using is not a process instance but a child execution and there it throws the exception after execution.isProcessInstanceType is false. You can solve the issue with providing the process instance id instead of the child execution id.

**Comment by zywhmj** [comment]
But it's a problem on Linux, it's a problem on Windows

**Comment by zywhmj** [comment]
But running on Linux is a problem

**Comment by zywhmj** [comment]
But running on Linux has this problem
