### ISSUE TITLE
Big ACT_GE_BYTEARRAY TABLE with 2TB capacity and 1.8 billion Rows

### ISSUE THREAD

**Issue by mf1632015** [flowable/flowable-engine#3422]
**Is your feature request related to a problem? Please describe.**

As description in title, in our BPMN flows, we have so many big variables. And these big variables will be inserted into ACT_GE_BYTEARRAY Table. We have an ACT_GE_BYTEARRAY table with 2TB capacity and 1.8 billinon rows.

**Describe the solution you'd like**

I want to split ACT_GE_BYTEARRAY  to big variables table and process definitions table. and Add Date Column, So We can create partition tables and drop them as you can.

**Describe alternatives you've considered**

Our temp solution is migrating the process definitions line to a new table and  drop the older one. Then we rename the new table to ACT_GE_BYTEARRAY.  
But it always causes some process instances problems.

**Comment by mf1632015** [comment]
@falko @joshlong @nikku @rhubarb

**Comment by filiphr** [comment]
@mf1632015 there is no need to ping anyone. You need to be patient and give us time to review this request.

What is stopping you to partition the tables even now? You can decide what your partition key is.

**Comment by mf1632015** [comment]
@filiphr May you help me？

**Comment by filiphr** [comment]
@mf1632015 as I said yesterday in https://github.com/flowable/flowable-engine/issues/3422#issuecomment-1209072971 there is no need to ping anyone and you have to be patient. 

If you want to clean up things I would suggest that you look into the [History Cleaning](https://www.flowable.com/open-source/docs/bpmn/ch11-History/#history-cleaning) that we have added in recent versions instead of doing something on the DB table level.

I am going to close this now since there isn't much that we can do on the engine level. If you have further questions I would suggest posting on our [forum](https://forum.flowable.com/).
