### ISSUE TITLE
TaskService.getIdentityLinksForTask(taskId)

### ISSUE THREAD

**Issue by maratkalibek** [flowable/flowable-engine#3467]
**Describe the bug**

TaskService.getIdentityLInksForTask(taskId) is duplicating IdentityLink in results. Looks like same IdentityLink added to list twice.

**Expected behavior**

TaskService.getIdentityLInksForTask(taskId) should not duplicate IdentityLink in results.

**Code**

![image](https://user-images.githubusercontent.com/4571314/190918885-3d8a813f-158c-42f9-ac9e-4719126257ce.png)

**Additional context**

https://github.com/flowable/flowable-engine/blob/main/modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java#L247-L270

Here, getCandidates method returns set, but getIdentityLinks returns map. So duplicates are removed for getCandidates method.

**Comment by kendoziyu** [comment]
I've had a similar issue too. This problem is easy to reproduce.

**Flowable Engine Version**
As of the latest 6.7.2-release, this issue has not been resolved
```
<dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-engine</artifactId>
    <version>6.7.2</version>
</dependency>
```

**How to reproduce**
Just follow the [Getting Started](https://www.flowable.com/open-source/docs/bpmn/ch02-GettingStarted).

Here is my sample project zip package：
[flowable-example.zip](https://github.com/flowable/flowable-engine/files/10111322/flowable-example.zip)


Set the breakpoint to `org.flowable.engine.impl.util.IdentityLinkUtil` as shown
<img width="839" alt="taskEntity getIdentityLinks" src="https://user-images.githubusercontent.com/18433396/204482467-14c1743f-f33b-4b83-a76f-85afdc871c0d.png">

Then you see the problem
<img width="855" alt="issue" src="https://user-images.githubusercontent.com/18433396/204483741-48077c43-43da-4e00-8b95-0a6f5ffb3003.png">

**Comment by arthware** [comment]
Quickly checked this: This is a runtime behavior inconsistency on the TaskEntity, which seems to happen only during process execution. Problem is gone, when the task is loaded again, or the taskService.getIdentityLinksForTask method is used. 

Root cause of the problem is, that taskEntityImpl#getIdentityLinks is not a simple getter like expected, but it initializes identity links too. 

The identityLink gets initially created (and persisted) in [UserTaskActivityBehavior](https://github.com/flowable/flowable-engine/blob/97277a611624b83cba83d55b1d712332d31bb7f5/modules/flowable-engine/src/main/java/org/flowable/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java#L375)

And then twice here (once because the unexpected side-effect in taskEntity.getIdentityLinks()): 

[IdentityLinkUtil.java#L90](https://github.com/flowable/flowable-engine/blob/982be7e47facf17bb779571ba663bdf8f86947a3/modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/util/IdentityLinkUtil.java#L90)

The TaskEntityImpl getter: 
https://github.com/flowable/flowable-engine/blob/02b22f89af90516a921fcc921ea0bee21d72f8c5/modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/persistence/entity/TaskEntityImpl.java#L261-L262

In general that is not so nice, because the getter does not even work, when it is called outside of an execution (with a NPE).
