### ISSUE TITLE
Spring Boot v3.0

### ISSUE THREAD

**Issue by Stexxen** [flowable/flowable-engine#3520]
With the imminent arrival of Spring Boot v3.0 with all its jakarta.*  namespace changes.

If wondered of there was a timeline of a prototype or maybe even a release candidate?

**Comment by filiphr** [comment]
Have a look at my comment in https://github.com/flowable/flowable-engine/issues/3489#issuecomment-1280931053.

Due to the jakarta namespace changes we won't be able to support both Spring Boot 3.x and Spring Boot 2.x. This means that we would need to migrate the entire project. 

Closing this issue in favour of #3489
