### ISSUE TITLE
Event Logging docs incorrect

### ISSUE THREAD

**Issue by aaronkavlie-wf** [flowable/flowable-engine#361]
The [Event Logging](http://www.flowable.org/docs/userguide/index.html#advanced.event.logging) section of the docs is outdated:

- `ProcessEngineConfiguration` does not have a `setEnableDatabaseEventLogging` method
- There is no `EventLogger` constructor that just takes a `Clock`.

In addition, it's unclear how the event logger actually works — what does its output look like, and how do you query it?

**Comment by tijsrademakers** [comment]
Docs are updated with correct method call. The docs could still be extended with more explanation about the event logger structure. But it basically stores all process engine events and you there are not a lot of query options, because the event is stored in JSON text. The idea is that you can use this event logger to process all process engine events asynchronously to store data in another data source.
