### ISSUE TITLE
Unable to pause and resume execution in workflow process

### ISSUE THREAD

**Issue by aamittsinghh** [flowable/flowable-engine#3678]
My use case is i want to pause the process for some duration and then resume the process again .
I used startProcessByID which returns ID on async start .

post that i thried using suspendProccessByID to pause/ supend the process and i can use that Id again to resume /activate process by  ID 

but while suspending i get error prompted particular table ACT-Ru is in use transaction locked .

does any body know how to achieve this usecase

**Comment by tijsrademakers** [comment]
Please use the user forum for questions. When you are using async logic in the process model, then when calling the suspend process method it is possible that the async process logic is executed at that moment as well. That's why you get the exception. You can retry calling the suspend process method after a certain delay.
