### ISSUE TITLE
Nullpointer exception on deleting historic case instance when entityLinks is not enabled.

### ISSUE THREAD

**Issue by jombie** [flowable/flowable-engine#3745]
**Describe the bug**
Nullpointer exception on deleting historic case instance when entityLinks is not enabled.

**Expected behavior**
Null check or `enableEntityLinks` check should be done to avoid nullPointer exception.

**Code**
   ```
 cmmnHistoryService
        .createHistoricCaseInstanceQuery()
        .caseInstanceId(caseInstanceId)
        .deleteWithRelatedData();
```

**Additional context**
Flowable version: 6.8.0
Flowable with spring boot

**Comment by jombie** [comment]
Fix for the same: https://github.com/flowable/flowable-engine/pull/3746

**Comment by filiphr** [comment]
Thanks for the fix @jombie. Apart from the fix. We would actually suggest using something like

```java
cmmnHistoryService
     .createHistoricCaseInstanceQuery()
     .caseInstanceId(caseInstanceId)
     .deleteSequentiallyUsingBatch(10, "Test");
```

Instead of the `deelteWithRelatedData`. 

If you only want to delete a single case instance you can also use `cmmHistoryService.deleteHistoricCaseInstance(caseInstanceId)`. That deletes the right data in the right way as well
