### ISSUE TITLE
How to optimize flowable after millions of data volumes

### ISSUE THREAD

**Issue by BruceGC** [flowable/flowable-engine#3975]
Can it be divided into databases, tables or archives? Is there a mature solution that I can refer to?

**Comment by tijsrademakers** [comment]
Not sure where this question comes from, can you elaborate a bit more?
Relational databases are in general quite good at handling large data volumes.

**Comment by BruceGC** [comment]
My process has reached tens of millions, so the amount of data in the flowable is also very large, which causes each query to the related table to be very slow. I want to know if there is a solution that can help me solve this problem.

**Comment by tijsrademakers** [comment]
For which database is this? And wow did you size your database server with CPU and memory?
You can delete completed historic data that is older than a specific time period. And there are various options to configure the history settings for processes, so that unnecessary data is not kept in the history tables.

**Comment by BruceGC** [comment]
> You can gain some performance with adding DB indexes. If you store data in process/case variables you could create dedicated structures for them.

If you store data in process/case variables you could create dedicated structures for them.  -- Could you please give me an example and explain in detail how to operate it? Thank you

**Comment by BruceGC** [comment]
> For which database is this? And wow did you size your database server with CPU and memory? You can delete completed historic data that is older than a specific time period. And there are various options to configure the history settings for processes, so that unnecessary data is not kept in the history tables.

The hardware should currently be optimal within its capabilities. In addition to upgrading hardware, does deleting historical data mean directly physically deleting data through SQL? 
And there are various options to configure the history settings for processes, so that unnecessary data is not kept in the history tables -- There is still a suitable API to accomplish this. Where can I see the corresponding configuration options?

**Comment by filiphr** [comment]
Closing this since it goes more in the direction of a question, rather then a Flowable problem. Please use the [Forum](https://forum.flowable.org/) for asking questions.

Have a look at [Housekeeping](https://documentation.flowable.com/latest/howto/howto/howto-housekeeping) in the documentation for what you can do to clean up data.

You can also have a look at the [History Level Configuration](https://documentation.flowable.com/latest/develop/be/history-level) and [History](https://www.flowable.com/open-source/docs/bpmn/ch10-History) in the documentation for more information as well
