### ISSUE TITLE
Build fails due to FlowableEngineEvent package move

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#528]
Current master fails to build (`mvn -Pdistro,nodocs clean install`) with compile errors "cannot find symbol: class FlowableEngineEvent". These seem due to the move of that class to package `org.flowable.engine.delegate.event`. Another issue are missing function implementations for `getExecution()` on a few `Impl` classes.

Despite this, the Travis build was surprisingly _green_. Huh?! The issue turns out to be with the Travis job spec. It does `mvn clean install` without the `-Pdistro`, which builds only 17 of Flowable's 51 modules. Cheeky! ;-)

**Comment by tijsrademakers** [comment]
Hi Marco,

Should be fixed now. Yes we removed getExecution from Task and Job because we needed to separate the task, identity link, variable, and job services in separate modules so they can be reused by the CMMN engine. It should not cause a big issue because you can still set variables etc. Let us know if you see issues with getExecution not being available directly.

The Travis build is only a simple first test run and we can't do the distro build there because it gives back memory and timing errors then. We also have our Jenkins QA box that does a lot more testing (http://qa.flowable.org)
