### ISSUE TITLE
Error deploying app if an included form contains a dropdown (6.3.0)

### ISSUE THREAD

**Issue by Tarekajaj** [flowable/flowable-engine#957]
Hello again,

We are having an issue with the latest release (6.3.0),
Using the modeler app we added dropdown field to test the new expression feature,
and then when trying to publish a new version of the app we get the follolwing error

> Invalid deploy result code: HTTP/1.1 500 Internal Server Error
![image](https://user-images.githubusercontent.com/11189145/38356682-0b90754e-38c9-11e8-8263-f96b9fd9e01a.png)

W tried with static options for the dropdown and the problem persisted. we removed the dropdown field and the app was published successfully.

Any idea what's going wrong?

**Comment by Tarekajaj** [comment]
The problem is also happening when using

**Comment by martin-grofcik** [comment]
if you are using spring-boot try to set property -Dflowable.modeler.app.deployment-api-url=http://localhost:9999/flowable-task/process-api
the default port is 8080

**Comment by filiphr** [comment]
@Tarekajaj how are you starting the application? Are you deploying the wars in an application servlet? Also can you send us the output of your logs?

**Comment by Tarekajaj** [comment]
@filiphr Yes, we Just deploy war files in a tomcat server,
We were using a mysql datasource (could it be the reason that database tables were not updated?),
I just replaced the war files with the latest version and restarted the server, and everything stopped working,
I will try with a fresh install and report back.

**Comment by Tarekajaj** [comment]
@filiphr please find attached the logs.

[log.txt](https://github.com/flowable/flowable-engine/files/1879499/log.txt)

**Comment by filiphr** [comment]
@Tarekajaj unfortunately the required backwards compatible dependency from Spring Boot (that migrates your old properties) is runtime scope. We are going to fix this for 6.3.1. For the time being you should add the following dependencies to your tomcat lib folder:

* [spring-boot-properties-migrator](http://central.maven.org/maven2/org/springframework/boot/spring-boot-properties-migrator/2.0.0.RELEASE/spring-boot-properties-migrator-2.0.0.RELEASE.jar)
* [spring-boot-configuration-metadata](http://central.maven.org/maven2/org/springframework/boot/spring-boot-configuration-metadata/2.0.0.RELEASE/spring-boot-configuration-metadata-2.0.0.RELEASE.jar)

Also reason why you can't deploy is because the task app was not even started. There are exceptions in your logs

**Comment by Tarekajaj** [comment]
@filiphr Thank you for the hint,
Unfortunately that did not help, added the libraries and redeployed the war files but got the same result,
I can see a database exception in the log:
`org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 172.29.164.209:9091" [90067-196]`

I couldn't figure out where 172.29.164.209 came from, search a little bit and found this line in application.properties of each app:
`spring.datasource.url=jdbc:h2:~/flowable-db/db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9091;DB_CLOSE_DELAY=-1`
changed it to
`spring.datasource.url=jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1`
 and every thing deployed successfully,

Also the tried adding dropdown to a form in a model and publishing it and everything worked without a problem,

Will try using mysql and report any problem, but we can close the issue for now.

Many thanks
